GPP-Woo/GPP-app

.editorconfig, .gitattributes, ODPC.Server/Authentication/AuthOptions.cs, ODPC.Server/Authentication/AuthenticationExtensions.cs, ODPC.Server/Authentication/OdpUser.cs, ODPC.Server/Config/SecurityHeaders.cs, ODPC.Server/Config/StaticFileCacheHeaders.cs, ODPC.Server/ODPC.csproj, ODPC.Server/Program.cs, ODPC.Server/appsettings.json, ODPC.sln, README.md, docker-compose.yml, odpc.client/src/api/fetch-logged-in.ts, odpc.client/src/components/HelloWorld.vue, odpc.client/src/components/UserProfile.vue, odpc.client/vite.config.ts
=> feat: login via oidc

odpc.client/src/features/publicatie/components/DocumentForm.vue, odpc.client/src/features/publicatie/types.ts, odpc.client/src/features/publicatie/use-documenten.ts
- Doorstrepen ingetrokken documentnaam
- Default documenttitel
=> Meerdere documenten test opmerkingen

ODPC.Server/Features/Publicaties/Publicatie.cs, ODPC.Server/Features/Publicaties/PublicatiesMock.cs, odpc.client/src/assets/main.scss, odpc.client/src/assets/simple.css, odpc.client/src/components/DateRangePicker.vue, odpc.client/src/composables/use-paged-search.ts, odpc.client/src/features/publicatie/PublicatieDetails.vue, odpc.client/src/features/publicatie/PublicatiesOverview.vue, odpc.client/src/features/publicatie/components/DocumentForm.vue, odpc.client/src/features/publicatie/components/PublicatieForm.vue, odpc.client/src/features/publicatie/composables/use-publicatie.ts, odpc.client/src/features/publicatie/types.ts, odpc.client/src/router/index.ts, odpc.client/src/views/PublicatiesView.vue
Pull request voor stories #9 en #39
=> 9 odpc muteren bestaande publicatie

ODPC.Server/Authentication/AuthenticationExtensions.cs
=> fix: make sure the return path is relative in the challenge endpoint

ODPC.Server/Program.cs
=> fix: request logging met serilog

.github/workflows/docker-image.yml
=> Create release 1.0.0

.dockerignore
=> add env to docker build

odpc.client/src/components/DateRangePicker.vue, odpc.client/src/features/publicatie/PublicatiesOverview.vue
=> fix: zoek op datum tot en met

ODPC.Server/Features/Formats/FormatsMock.cs, odpc.client/src/features/publicatie/components/DocumentForm.vue
=> fix for mimetype fallback

odpc.client/src/features/publicatie/components/DocumentDetailsForm.vue
=> #127 voeg creatiedatum toe aan documenten

odpc.client/src/components/PromptModal.vue, odpc.client/src/composables/use-multiple-confirm-dialogs.ts, odpc.client/src/features/publicatie/PublicatieDetails.vue, odpc.client/src/features/publicatie/dialogs.ts
=> #143 waarschuwing bij publicatie zonder document

odpc.client/src/features/publicatie/components/DocumentDetailsForm.vue
=> #174 Datum document mag niet in de toekomst liggen

odpc.client/src/features/gebruikersgroep/components/GebruikersgroepForm.vue, odpc.client/src/features/publicatie/components/DocumentDetailsForm.vue, odpc.client/src/features/publicatie/components/DocumentenForm.vue, odpc.client/src/features/publicatie/components/PublicatieForm.vue, odpc.client/src/features/publicatie/composables/use-documenten.ts, odpc.client/src/features/publicatie/types.ts
#157 inclusief bug fix voor retry en trimmen van required fields
=> #157 beperkingen op status wisselingen

docs/requirements.txt
Resolved by re-generating requirements.txt
=> fix vulnerability in docs build

odpc.client/src/assets/base.css, odpc.client/src/assets/main.scss, odpc.client/src/features/publicatie/PublicatiesOverview.vue, odpc.client/src/features/publicatie/components/DocumentDetailsForm.vue
[Enhancements](https://github.com/GPP-Woo/GPP-app/issues/161#issuecomment-2962810193)
=> #161 opslaan als concept en redesign knoppen irt status

ODPC.Server/Features/Documenten/DocumentenOverzicht/DocumentenOverzichtController.cs, ODPC.Server/Features/Documenten/PublicatieDocument.cs, ODPC.Server/Features/Publicaties/Publicatie.cs, odpc.client/src/assets/base.css, odpc.client/src/components/AddRemoveItems.vue, odpc.client/src/features/gebruikersgroep/components/GebruikersgroepForm.vue, odpc.client/src/features/publicatie/components/DocumentDetailsForm.vue, odpc.client/src/features/publicatie/components/PublicatieForm.vue, odpc.client/src/features/publicatie/composables/use-kenmerken.ts, odpc.client/src/features/publicatie/types.ts
Dit is gecombineerd PR voor #125 en #126
=> #126 voeg identifiers toe aan publicaties

odpc.client/src/features/publicatie/components/PublicatiesOverviewFilter.vue, odpc.client/src/features/publicatie/components/PublicatiesOverviewSearch.vue
[Test feedback](https://github.com/GPP-Woo/GPP-app/issues/196#issuecomment-3043958166)
=> #196 meer filters op mijn publicaties

ODPC.Server/Features/Publicaties/Publicatie.cs
=> #211 parse ontbrekende velden niet naar null maar weglaten

ODPC.Server/Features/Formats/FormatsOverzicht/FormatsOverzichtController.cs, ODPC.Server/Features/Gebruikersgroepen/AlleGebruikersgroepen/GebruikersgroepenController.cs, ODPC.Server/Features/Gebruikersgroepen/GebruikersgroepDetails/GebruikersgroepDetailsController.cs, ODPC.Server/Features/Gebruikersgroepen/GebruikersgroepUpsert/GebruikersgroepAanmaken/GebruikersgroepAanmakenController.cs, ODPC.Server/Features/Gebruikersgroepen/GebruikersgroepUpsert/GebruikersgroepBijwerken/GebruikersgroepBijwerkenController.cs, ODPC.Server/Features/Gebruikersgroepen/GebruikersgroepVerwijderen/GebruikersgroepVerwijderenController.cs, ODPC.Server/Features/Gebruikersgroepen/MijnGebruikersgroepen/GebruikersgroepenController.cs, odpc.client/src/composables/use-app-data.ts, odpc.client/src/composables/use-paged-search.ts, odpc.client/src/features/gebruikersgroep/GebruikersgroepenOverview.vue, odpc.client/src/features/gebruikersgroep/composables/use-gebruikersgroep.ts, odpc.client/src/features/publicatie/components/DocumentDetailsForm.vue, odpc.client/src/features/publicatie/composables/use-documenten.ts, odpc.client/src/features/publicatie/composables/use-mijn-gebruikersgroepen.ts, odpc.client/src/features/publicatie/composables/use-mijn-waardelijsten.ts, odpc.client/src/features/publicatie/composables/use-publicatie.ts, odpc.client/src/features/publicatie/service.ts
=> use api v2

odpc.client/src/components/InfoPopover.vue, odpc.client/src/features/gebruikersgroep/components/WaardelijstenForm.vue, odpc.client/src/features/publicatie/PublicatiesOverview.vue
=> #220 positionering omschrijving bij informatiecategorie
